require('./init')
const { https } = require('firebase-functions')
module.exports.profiles = https.onRequest(require('./src/profiles'))
module.exports.battles = https.onRequest(require('./src/battles'))
module.exports.votes = https.onRequest(require('./src/votes'))
module.exports.invitations = https.onRequest(require('./src/invitations'))
